In [56]:
import numpy as np
import lda
import pandas as pd
import lda.datasets


In [57]:
#X = lda.datasets.load_reuters() 
#document term matrix를 x변수에 대입

In [58]:
X = lda.datasets.load_reuters()
print(X)

[[1 0 1 ... 0 0 0]
 [7 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]]


In [59]:
vocab = lda.datasets.load_reuters_vocab()
#r = open('example_word.txt', mode='rt', encoding='utf-8')
#vocab = r.read()
#example 데이터의 단어집을 vocab에 저장

In [60]:
titles = lda.datasets.load_reuters_titles()
#example 데이터의 문장들을 titles 변수에 저장한다.
#titles = pd.read_csv('마이홈 - 꿈의 디자인_review.csv')
print(titles[0])

0 UK: Prince Charles spearheads British royal revolution. LONDON 1996-08-20


In [61]:
model = lda.LDA(n_topics=20, n_iter=1500, random_state=1)
#lda 알고리즘 모델을 초기화, n_topics = 20 -> 20개의 토픽 집단을 생성한다.
print(model)

In [62]:
model.fit(X)
#initial

INFO:lda:n_documents: 395
INFO:lda:vocab_size: 4258
INFO:lda:n_words: 84010
INFO:lda:n_topics: 20
INFO:lda:n_iter: 1500
INFO:lda:<0> log likelihood: -1051748
INFO:lda:<10> log likelihood: -719800
INFO:lda:<20> log likelihood: -699115
INFO:lda:<30> log likelihood: -689370
INFO:lda:<40> log likelihood: -684918
INFO:lda:<50> log likelihood: -681322
INFO:lda:<60> log likelihood: -678979
INFO:lda:<70> log likelihood: -676598
INFO:lda:<80> log likelihood: -675383
INFO:lda:<90> log likelihood: -673316
INFO:lda:<100> log likelihood: -672761
INFO:lda:<110> log likelihood: -671320
INFO:lda:<120> log likelihood: -669744
INFO:lda:<130> log likelihood: -669292
INFO:lda:<140> log likelihood: -667940
INFO:lda:<150> log likelihood: -668038
INFO:lda:<160> log likelihood: -667429
INFO:lda:<170> log likelihood: -666475
INFO:lda:<180> log likelihood: -665562
INFO:lda:<190> log likelihood: -664920
INFO:lda:<200> log likelihood: -664979
INFO:lda:<210> log likelihood: -664722
INFO:lda:<220> log likelihood: -

In [63]:
topic_word = model.topic_word_
#초기화된 lda 알고리즘 모델에 준비된 document term matrix를 전달하여 트레이닝 시킨다.
print(topic_word)

[[3.62505347e-06 3.62505347e-06 3.62505347e-06 ... 3.62505347e-06
  3.62505347e-06 3.62505347e-06]
 [1.87498968e-02 1.17916463e-06 1.17916463e-06 ... 1.17916463e-06
  1.17916463e-06 1.17916463e-06]
 [1.52206232e-03 5.05668544e-06 4.05040504e-03 ... 5.05668544e-06
  5.05668544e-06 5.05668544e-06]
 ...
 [4.17266923e-02 3.93610908e-06 9.05698699e-03 ... 3.93610908e-06
  3.93610908e-06 3.93610908e-06]
 [2.37609835e-06 2.37609835e-06 2.37609835e-06 ... 2.37609835e-06
  2.37609835e-06 2.37609835e-06]
 [3.46310752e-06 3.46310752e-06 3.46310752e-06 ... 3.46310752e-06
  3.46310752e-06 3.46310752e-06]]


In [64]:
n_top_word = 9

In [65]:
for i, topic_dist in enumerate(topic_word):
    topic_word = np.array(vocab)[np.argsort(topic_dist)][:-(n_top_word+1):-1]
    print('Topic {}: {}'.format(i, ' '.join(topic_word)))
    
    #topic 0 ~ topic 19까지 만들어짐, topic 집단의 상위 score 8개만 출력됨

Topic 0: british churchill sale million major letters west britain john
Topic 1: church government political country state people party against first
Topic 2: elvis king fans presley life concert young death every
Topic 3: yeltsin russian russia president kremlin moscow michael operation orthodox
Topic 4: pope vatican paul john surgery hospital pontiff rome mass
Topic 5: family funeral police miami versace cunanan city service home
Topic 6: simpson former years court president wife south church york
Topic 7: order mother successor election nuns church nirmala head sister
Topic 8: charles prince diana royal king queen parker bowles camilla
Topic 9: film french france against bardot paris poster animal festival
Topic 10: germany german war nazi letter christian book jews scientology
Topic 11: east peace prize award timor quebec belo leader indonesia
Topic 12: n't life show told very love television father come
Topic 13: years year time last church world people say during
Topic 14: mother

In [66]:
doc_topic = model.doc_topic_

In [67]:
for i in range(10):
    print("{} (top topic: {})".format(titles[i], doc_topic[i].argmax()))

0 UK: Prince Charles spearheads British royal revolution. LONDON 1996-08-20 (top topic: 8)
1 GERMANY: Historic Dresden church rising from WW2 ashes. DRESDEN, Germany 1996-08-21 (top topic: 13)
2 INDIA: Mother Teresa's condition said still unstable. CALCUTTA 1996-08-23 (top topic: 14)
3 UK: Palace warns British weekly over Charles pictures. LONDON 1996-08-25 (top topic: 8)
4 INDIA: Mother Teresa, slightly stronger, blesses nuns. CALCUTTA 1996-08-25 (top topic: 14)
5 INDIA: Mother Teresa's condition unchanged, thousands pray. CALCUTTA 1996-08-25 (top topic: 14)
6 INDIA: Mother Teresa shows signs of strength, blesses nuns. CALCUTTA 1996-08-26 (top topic: 14)
7 INDIA: Mother Teresa's condition improves, many pray. CALCUTTA, India 1996-08-25 (top topic: 14)
8 INDIA: Mother Teresa improves, nuns pray for "miracle". CALCUTTA 1996-08-26 (top topic: 14)
9 UK: Charles under fire over prospect of Queen Camilla. LONDON 1996-08-26 (top topic: 8)
